apiVersion: v1   
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    name: {{ .Values.service.name }}
spec:
  ports:
  - port: {{ .Values.service.ports.port }}
    targetPort: {{ .Values.service.ports.targetPort }}
  clusterIP: {{ .Values.service.clusterIp }}
  selector:
    role: {{ .Values.service.name }}



