apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
spec:
  ports:
  - port:  {{ .Values.service.ports.port }}
    protocol: TCP
    targetPort: {{ .Values.service.ports.targetPort }}
  selector:
    app: {{ .Values.service.name }}
status:
  loadBalancer: {}



