apiVersion: apps/v1   
kind: StatefulSet
metadata:
  name: {{ .Values.all.name }}
spec:
  serviceName: {{ .Values.all.name }}
  replicas: 2
  selector:
    matchLabels:
      role: {{ .Values.all.name }}
  template:
    metadata:
      labels:
        role: {{ .Values.all.name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Values.all.name }}
          image: {{ .Values.container.image }}
          command:
            - mongod
            - "--replSet"
            - rs0
          ports:
            - containerPort: {{ .Values.container.ports.containerPort }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc