apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.all.name }}
  name: {{ .Values.all.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.all.name }}
  serviceName: "mongo"
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.all.name }}
    spec:
      containers:
      - image: {{ .Values.container.image }}
        name: {{ .Values.all.name }}
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: {{ .Values.env.MONGO_INITDB_ROOT_USERNAME }}
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: {{ .Values.env.MONGO_INITDB_ROOT_PASSWORD }}
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-data
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
        