imagePullSecrets:
  name: acrpatsecret
  
container:
  image: mongo:4.4
  pullPolicy: Always
  ports:
    name: web
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

env:
  MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
  MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
  
service:
  name: mongosvc
  type: ClusterIP
  ports:
      protocol: TCP
      port: 27017
      targetPort: 27017

all:
  name: mongodb