imagePullSecrets:
  name: acrpatsecret
  
container:
  image: $REGISTRY/$GITHUB_REPO_OWNER/$GITHUB_REPO_NAME:$GENERAL_TAG
  tag: $GENERAL_TAG
  pullPolicy: Always
  ports:
    name: web
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

env:
  ME_CONFIG_MONGODB_ADMINUSERNAME: root
  ME_CONFIG_MONGODB_ADMINPASSWORD: example
  ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  

service:
  name: mongoDB
  type: ClusterIP
  ports:
      protocol: TCP
      port: 80
      targetPort: 80

all:
  name: mongoDB