apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.all.name }}
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
  selector:
    app: {{ .Values.all.name }}


