apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.all.name }}
spec:
  template:
    metadata:
      name: {{ .Values.all.name }}
      labels:
        app: {{ .Values.all.name }}
    spec:
      containers:
        - name: {{ .Values.all.name }}
          image: {{ .Values.container.image }}
          imagePullPolicy: {{ .Values.container.pullPolicy }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.env.MONGO_INITDB_ROOT_USERNAME }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.env.MONGO_INITDB_ROOT_PASSWORD }}
          ports:
          - name: {{ .Values.container.ports.name }}
            containerPort: 27017
          resources:
            requests:
              memory: {{ .Values.container.resources.requests.memory }}
              cpu: {{ .Values.container.resources.requests.cpu }}
            limits:
              memory: {{ .Values.container.resources.limits.memory }}
              cpu: {{ .Values.container.resources.limits.cpu }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
  selector:
    matchLabels:
      app: {{ .Values.all.name }}