container:
  image: mongo:4.4
  
env:
  MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
  MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
  
service:
  name: mongo
  ports:
      port: 27017
      targetPort: 27017

all:
  name: mongo