name: Build and Deploy the app when is merged to main branch

on:
   push:
     branches:
       - main

jobs:
  Build-Application:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Generate General Tag (Run Date and GitHub Run Number)
        run: echo "GENERAL_TAG=$(date +'%Y%m%d_'$GITHUB_RUN_NUMBER)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push application image to DockerHub Container Registry
        uses: docker/build-push-action@v4
        with:
          tags: cadu1982/app:${{ env.GENERAL_TAG }}
          push: true
        
    outputs:
      general-tag: ${{ env.GENERAL_TAG }}

#=========================================================================================================================

  Deploy:
    runs-on: [self-hosted, carlos-primeup]
   
    env:
      SERVER: dev
      GENERAL_TAG: ${{ needs.Build-Application.outputs.general-tag }}
    needs: ["Build-Application"]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

  #     - name: Azure Login
  #       uses: Azure/login@v1.4.5
  #       with:
  #         creds: ${{ secrets.ABD1SPGHWF001 }}
      
  #     - name: Delete dir .kube 
  #       run: |
  #         cd $HOME
  #         rm -r .kube

  #     - name: Login in AKS
  #       run: az aks get-credentials --resource-group ${{ env.RG_AKS }} --name ${{ env.NAME_AKS }} --admin

      - name: Replace Environment Variables
        run: envsubst < ./k8s/values-${{ env.SERVER }}.yaml > ./k8s/values-${{ env.SERVER }}-rplc.yaml
        env:
          ME_CONFIG_MONGODB_ADMINUSERNAME: ${{ secrets.ME_CONFIG_MONGODB_ADMINUSERNAME }}
          ME_CONFIG_MONGODB_ADMINPASSWORD: ${{ secrets.ME_CONFIG_MONGODB_ADMINPASSWORD }}
          
      - name: Deploy MondoDB
        run: |
          helm upgrade --install mongodb ./k8s -f ./k8s/values-${{ env.SERVER }}-rplc.yaml
      
      - name: Replace Environment Variables
        run: envsubst < ./k8s1/values-${{ env.SERVER }}.yaml > ./k8s1/values-${{ env.SERVER }}-rplc.yaml
        env:
          GENERAL_TAG: ${{ env.GENERAL_TAG }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
                
      - name: Deploy App
        run: |
          helm upgrade --install app ./k8s1 -f ./k8s1/values-${{ env.SERVER }}-rplc.yaml

  


  

      