name: Build and Deploy the app when is merged to main branch

on:
   push:
     branches:
       - main

jobs:
  Build-Application:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Generate General Tag (Run Date and GitHub Run Number)
        run: echo "GENERAL_TAG=$(date +'%Y%m%d_'$GITHUB_RUN_NUMBER)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push application image to DockerHub Container Registry
        uses: docker/build-push-action@v4
        with:
          tags: cadu1982/app:${{ env.GENERAL_TAG }}
          push: true
        
    outputs:
      general-tag: ${{ env.GENERAL_TAG }}

#=========================================================================================================================

  Deploy:
    runs-on: [self-hosted, carlos-primeup]
   
    env:
      SERVER: dev
      GENERAL_TAG: ${{ needs.Build-Application.outputs.general-tag }}
      NAME_EKS: infra
      REGION: us-eats-1
    needs: ["Build-Application"]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0 

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      #     aws-region: us-east-1
      #     mask-aws-account-id: true
      
      - name: Configure EKS 
        run:  aws eks update-kubeconfig --region ${{ env.REGION }} --name ${{ env.NAME_EKS }}

      - name: Replace Environment Variables
        run: envsubst < ./k8s_db/values-${{ env.SERVER }}.yaml > ./k8s_db/values-${{ env.SERVER }}-rplc.yaml
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }} 
          
      - name: Deploy MondoDB
        run: |
          helm upgrade --install mongodb ./k8s_db -f ./k8s_db/values-${{ env.SERVER }}-rplc.yaml
      
      - name: Replace Environment Variables
        run: envsubst < ./k8s_app/values-${{ env.SERVER }}.yaml > ./k8s_app/values-${{ env.SERVER }}-rplc.yaml
        env:
          GENERAL_TAG: ${{ env.GENERAL_TAG }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
                
      - name: Deploy App
        run: |
          helm upgrade --install app ./k8s_app -f ./k8s_app/values-${{ env.SERVER }}-rplc.yaml

  


  

      